// @ts-nocheck
/* eslint-disable */
/* prettier-ignore */

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Return the static build metadata. Infallible; no parameters; no
 * state.
 * 
 * Intended as the simplest possible Tauri command — if this
 * doesn't round-trip correctly, nothing else will. Also serves as
 * the canonical example of a sync `#[tauri::command]` with a
 * structured return type for future documentation.
 */
async version() : Promise<VersionInfo> {
    return await TAURI_INVOKE("version");
},
/**
 * Round-trip an input string through a blocking worker thread.
 * 
 * Exercises the canonical Win32-wrapping pattern: the closure runs
 * on a [`tokio::task::spawn_blocking`] pool worker (not the reactor
 * thread), sleeps for 60 ms to prove the `await` point genuinely
 * suspends, then returns `"pong: {input}"`.
 * 
 * Failure path: if the blocking task panics or is cancelled the
 * [`tokio::task::JoinError`] is mapped to
 * `system.spawn_blocking_failed`. Should never happen in steady
 * state — the closure is a sleep + `format!` with no fallible ops —
 * but the code path needs to exist so the pattern is complete for
 * the real Win32 wrappers in P10.2+.
 */
async ping(message: string) : Promise<Result<string, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ping", { message }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * TW / HK regular username+password login.
 * 
 * # Protocol
 * 
 * 1. Best-effort clear [`AppState::pending_totp`]
 * ([`AppState`]) so a stale continuation from an abandoned
 * HK-TOTP attempt cannot leak into the new login's error
 * surface.
 * 2. Mint a fresh [`BeanfunClient`] with region-appropriate
 * endpoints.
 * 3. Run [`login_with`] through the regular-family dispatcher.
 * 4. On success: stash `(client, session)` on [`AppState::auth`] and
 * return a [`SessionInfo`] DTO to the frontend.
 * 5. On [`LoginError::TotpRequired`]: stash `(client, challenge)`
 * on [`AppState::pending_totp`] and surface
 * `auth.totp_required` with a [`TotpChallengeInfo`] details
 * payload. The Vue layer is expected to render an OTP prompt
 * and call [`login_totp`] with the result.
 * 6. On every other [`LoginError`] variant: delegate to the P10.1
 * [`From<LoginError>`][`CommandError`] impl — including
 * [`LoginError::AdvanceCheckRequired`] which surfaces
 * `auth.advance_check_required` with the challenge URL for the
 * frontend to drive a verify flow.
 * 
 * # Why take `account` + `password` by value?
 * 
 * `#[tauri::command]` deserialises arguments from the JS invoke
 * payload into owned `String`s anyway; borrowing would force an
 * extra lifetime parameter that `specta` cannot round-trip. The
 * owned `String` is immediately wrapped in [`Credentials`] whose
 * [`Drop`] implementation zeroises the password byte buffer (via
 * `zeroize::ZeroizeOnDrop`), so the plaintext's lifetime is bounded
 * by the body of this function.
 * 
 * # Why mint a fresh client per call?
 * 
 * [`BeanfunClient`] owns the cookie jar. A re-login must begin with
 * a clean jar so stale `_SESSIONID` / `BFCOOKIE` cookies from the
 * previous attempt don't collide with the new one; WPF achieves the
 * same guarantee by instantiating a new `HttpClient` on every login
 * dialog open (Login.cs L38-41).
 */
async loginRegular(region: LoginRegion, account: string, password: string) : Promise<Result<SessionInfo, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("login_regular", { region, account, password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Complete an HK TOTP login by submitting the 6-digit code stored
 * on [`AppState::pending_totp`].
 * 
 * # Preconditions
 * 
 * Must be preceded by a [`login_regular`] call that resolved with
 * `auth.totp_required`. Otherwise surfaces [`TOTP_NOT_PENDING_CODE`].
 * 
 * # Behaviour on error
 * 
 * The pending slot is **retained** on error so the user can retry
 * with a corrected code (wrong OTP, transient network hiccup). It
 * is cleared only when:
 * 
 * - the call resolves with `Ok(session)` (the server accepted the
 * code, the challenge is consumed by design), or
 * - the user explicitly cancels via the `logout` command (D7).
 * 
 * See the module docs for the full state machine.
 * 
 * # Why `code` is a single `String` (not six)?
 * 
 * The IPC shape matches what the Vue form builds (`"123456"`);
 * splitting happens in [`split_otp_digits`] right before the
 * service call. The service layer's six-param signature mirrors
 * WPF's `otpCode1..6` 1:1 — we honour that at the call site
 * without forcing every TypeScript caller to destructure into six
 * boxes.
 */
async loginTotp(code: string) : Promise<Result<SessionInfo, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("login_totp", { code }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Begin a QR-code login flow — fetch the QR PNG, park the
 * continuation on [`AppState::pending_qr`], and return the
 * display payload.
 * 
 * # Preconditions
 * 
 * None. Calling this command repeatedly is the "refresh QR"
 * operation — each call mints a fresh [`BeanfunClient`] (clean
 * cookie jar) and overwrites any prior pending QR. Mirrors WPF
 * `MainWindow.xaml.cs::refreshQRCode()` which re-runs the whole
 * init sequence.
 * 
 * # Side effects
 * 
 * - Clears any prior `pending_totp` (switching login method
 * invalidates any half-finished TOTP continuation).
 * - Clears any prior `pending_qr` (explicit refresh semantics).
 * - Populates `pending_qr = Some((client, init))` on success so
 * [`login_qr_check`] can drive the poll / finalize cycle.
 * 
 * # Region restriction
 * 
 * QR login is **TW-only** — HK portal does not expose the same
 * `Login/InitLogin` endpoint (WPF disables the QR button under
 * `MainWindow.xaml.cs::loginMethodInit` L1099-1114). The region
 * parameter is kept for symmetry with [`login_regular`], but a
 * non-TW value bubbles up [`LoginError::QrUnsupportedRegion`]
 * (surfaces as `auth.qr_unsupported_region`).
 */
async loginQrStart(region: LoginRegion) : Promise<Result<QrStart, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("login_qr_start", { region }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Poll an active QR login for status — and on success, finalise
 * the login internally so the frontend gets a ready-to-use
 * [`SessionInfo`] in one round-trip.
 * 
 * # Preconditions
 * 
 * Must be preceded by a successful [`login_qr_start`]. Otherwise
 * surfaces [`QR_NOT_STARTED_CODE`] (`auth.qr_not_started`).
 * 
 * # State transitions
 * 
 * - [`QrPollOutcome::WaitLogin`] / [`QrPollOutcome::Failed`] —
 * pending slot kept; return `Pending` / `Retry`.
 * - [`QrPollOutcome::TokenExpired`] — pending slot cleared (the
 * challenge is consumed); return `Expired`. Frontend must call
 * [`login_qr_start`] again.
 * - [`QrPollOutcome::Approved`] — run
 * [`finalize_qr_login`][fin] with the same client, clear the
 * pending slot, populate [`AppState::auth`], and return
 * `Approved { session }`.
 * 
 * # Why finalize inline?
 * 
 * P10.2 Q5 = B: split the frontend-visible flow into two commands
 * (`start` + `check`) so the poll loop is frontend-driven, but
 * keep the terminal `finalize` step backend-internal so the
 * session secrets (`web_token`, `skey`) never cross IPC. A
 * hypothetical third `login_qr_finalize` command would either
 * duplicate this internal call or leak the init payload to the
 * frontend — neither aligns with the DRY / no-secrets
 * contracts.
 * 
 * [fin]: crate::services::beanfun::login::finalize_qr_login
 */
async loginQrCheck() : Promise<Result<QrStatus, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("login_qr_check") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open a fresh BeanfunClient + portal session key for a GamePass
 * login attempt and stash both on [`AppState::pending_gamepass`]
 * so a follow-up `open_gamepass_window` (CP3) can drive the
 * WebView leg.
 * 
 * # Behaviour
 * 
 * - **TW only.** Mirrors [`login_qr_start`]: the WPF
 * `MainWindow.xaml.cs::loginMethodInit` (L1099-1114) hides the
 * `btn_GamePass` button under HK, and the GamePass WebView path
 * hardcodes the TW `login.beanfun.com/GP/GPLoginInfo.aspx` host.
 * Non-TW callers receive `auth.gamepass_unsupported_region`
 * (mapped from [`LoginError::GamepassUnsupportedRegion`]) before
 * any HTTP traffic / window allocation.
 * - **Mints a fresh `BeanfunClient`** (TW endpoints) so the cookie
 * jar starts empty — exactly mirrors WPF
 * `gamepass_form.btn_OpenGamePass_Click` L52-53
 * (`var client = new BeanfunClient(); ... client.GetSessionkey()`),
 * which throws away any prior `App.MainWnd.bfClient` and starts
 * over. Cookie continuity from a prior login is intentionally
 * **not** desirable here: the GamePass leg must look like a
 * first-time portal visit so the WebView's pre-injected cookies
 * match the `bfClient`'s view of the world.
 * - **Returns `()`** because everything the frontend needs is
 * conveyed by the next event in the flow:
 * - `open_gamepass_window` (CP3) opens the WebView using the
 * stashed `skey`,
 * - `gamepass-login-success` / `gamepass-login-failed` Tauri
 * events surface the terminal outcome.
 * Keeping `skey` backend-internal matches the P10.2 Q4=C
 * "no secrets over IPC" stance shared with `pending_qr` /
 * `pending_totp`.
 * 
 * # Side effects
 * 
 * - Clears any prior `pending_totp` / `pending_qr` /
 * `pending_gamepass` (switching login method invalidates every
 * half-finished continuation, same stance as [`login_qr_start`]).
 * - Populates `pending_gamepass = Some((client, skey))` on success
 * so [`PendingGamepass`] can drive the CP3 WebView leg.
 * 
 * # Preconditions
 * 
 * - **No live GamePass WebView window.** If a prior
 * [`open_gamepass_window`] call's window is still alive we
 * refuse the call with [`GAMEPASS_WINDOW_ALREADY_OPEN_CODE`] —
 * the same typed error [`open_gamepass_window`] itself uses —
 * without touching any pending slot or minting a new client.
 * 
 * This guards against a subtle race surfaced in live test
 * 2026-04-18: if a user triggered a second
 * `login_gamepass_start` while an old GamePass window was still
 * up, this command would happily wipe `pending_gamepass` and
 * replace it with a fresh `(client, skey)`. The follow-up
 * `open_gamepass_window` would then reject with
 * `auth.gamepass_window_already_open` (correct), **but** the
 * still-live old window's [`handle_gamepass_window_destroyed`]
 * hook would misread the fresh pending slot as "user cancelled
 * this attempt" the moment the user closed the old window,
 * clearing the new slot and emitting a spurious
 * `gamepass-login-cancelled` event.
 * 
 * Pushing the window check up here forces the user through a
 * clean "close old → start new" transition — the same invariant
 * WPF enforces by allocating exactly one `GamePassBrowser` per
 * click (`gamepass_form.xaml.cs::btn_OpenGamePass_Click`
 * L37-59).
 * 
 * # Region restriction
 * 
 * GamePass is **TW-only** — same WPF guard as QR
 * (`MainWindow.xaml.cs::loginMethodInit` L1099-1114). The region
 * parameter is kept for symmetry with [`login_regular`] /
 * [`login_qr_start`], but a non-TW value bubbles up
 * [`LoginError::GamepassUnsupportedRegion`] (surfaces as
 * `auth.gamepass_unsupported_region`).
 * 
 * # Why the region check happens here, not in a service module
 * 
 * `login_gamepass_start` does not call any gamepass-specific
 * service function (the body is just `BeanfunClient::new` +
 * [`get_session_key`] + slot stash); the region guard is the only
 * logic that would justify a thin service wrapper. Inlining it
 * keeps the `services::beanfun::login::*` modules focused on
 * per-step HTTP calls (SRP) and avoids a `gamepass_start` shim
 * whose body would be a single `if`. CP3's
 * `complete_gamepass_login` will live in
 * `services/beanfun/login/gamepass.rs` because *that* one really
 * does drive multiple HTTP round-trips.
 */
async loginGamepassStart(region: LoginRegion) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("login_gamepass_start", { region }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open the GamePass WebView window and wire its page-load / destroy
 * hooks to the completion workers.
 * 
 * # Preconditions
 * 
 * Two distinct error codes guard the entry — keep the
 * distinction so operator logs and the Vue toast pipeline can
 * attribute the real cause:
 * 
 * - [`GAMEPASS_NOT_STARTED_CODE`] (`auth.gamepass_not_started`) —
 * no [`login_gamepass_start`] preceded this call, so
 * [`AppState::pending_gamepass`] is empty. Remediation: call
 * `login_gamepass_start` first.
 * - [`GAMEPASS_WINDOW_ALREADY_OPEN_CODE`]
 * (`auth.gamepass_window_already_open`) — a prior
 * [`tauri::WebviewWindow`] labelled [`GAMEPASS_WINDOW_LABEL`]
 * is still alive; WPF allocates exactly one `GamePassBrowser`
 * per login attempt (`gamepass_form.xaml.cs::btn_OpenGamePass_Click`
 * L37-59) and duplicating would race on the shared
 * `pending_gamepass` slot. Remediation: close the existing
 * window before retrying.
 * 
 * # Side effects
 * 
 * - Creates a single [`tauri::WebviewWindow`] labelled
 * [`GAMEPASS_WINDOW_LABEL`], navigating to
 * `https://login.beanfun.com/Login/Index?pSKey={skey}`.
 * - Injects [`GAMEPASS_AUTOCLICK_JS`] into every page the WebView
 * loads — harmless on non-GamePass pages (the `querySelector`
 * returns `null`).
 * - Attaches an `on_page_load` hook that spawns
 * [`handle_gamepass_page_load`] onto `tauri::async_runtime::spawn`
 * for each `PageLoadEvent::Finished` tick.
 * - Attaches an `on_window_event` hook that spawns
 * [`handle_gamepass_window_destroyed`] when the window is
 * destroyed (user cancel or programmatic close after success).
 * 
 * # Terminal outcomes
 * 
 * Never returned synchronously — the command resolves `Ok(())` as
 * soon as the WebView window is created. The real terminal outcome
 * arrives later via the Tauri event bus:
 * 
 * - [`GAMEPASS_SUCCESS_EVENT`] with [`SessionInfo`] payload — login
 * succeeded and [`AppState::auth`] is now populated.
 * - [`GAMEPASS_CANCELLED_EVENT`] — user closed the window before
 * completion; `pending_gamepass` cleared.
 * - [`GAMEPASS_FAILED_EVENT`] with [`CommandError`] payload — all
 * three harvest URLs failed on a page-load tick (defensive
 * surface for Tauri runtime regressions).
 * 
 * Keeping the `Ok(())` return separate from the success event
 * mirrors the P10.2 Q5=B split between "command success = flow
 * started" and "event delivery = flow terminal outcome" already
 * established by `login_qr_start` / `login_qr_check`.
 * 
 * # Why async?
 * 
 * Tauri's [`WebviewWindowBuilder::build`] deadlocks on Windows when
 * called from a synchronous command or event handler (WebView2
 * issue tracked upstream at wry#583). `async fn` hands the call
 * off to the tokio executor, which is a different thread from the
 * WebView2 message pump.
 */
async openGamepassWindow() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_gamepass_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch the AdvanceCheck.aspx page and park the verify
 * continuation on [`AppState::pending_verify`].
 * 
 * # Parameters
 * 
 * - `advance_check_url` — optional override URL (typically the one
 * carried by the prior `auth.advance_check_required` error's
 * `details.url`). `None` falls back to the static TW URL (same
 * fallback semantics as the service-layer fn).
 * 
 * # Side effects
 * 
 * - Overwrites any prior `pending_verify`. Re-running this command
 * is the "refresh verify page" operation (e.g. user cancelled and
 * kicked off a new verify flow).
 * - Does **not** touch `pending_totp` / `pending_qr`: a verify flow
 * is orthogonal to login (see [`PendingVerify`] docs).
 * 
 * # Why mint a fresh client?
 * 
 * See [`PendingVerify`] — verify lives on its own cookie jar so the
 * backend never holds a plaintext password across the verify
 * round-trips, and so a re-run produces deterministic state.
 */
async getVerifyPageInfo(advanceCheckUrl: string | null) : Promise<Result<VerifyPage, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_verify_page_info", { advanceCheckUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch the captcha image for the active verify flow.
 * 
 * # Preconditions
 * 
 * Must be preceded by [`get_verify_page_info`]; otherwise surfaces
 * [`VERIFY_NOT_STARTED_CODE`].
 * 
 * # Retry semantics
 * 
 * Safe to call multiple times — the server renders a fresh captcha
 * image for the same `samplecaptcha` id on each GET, so the Vue
 * UI's "reload captcha" button can just re-invoke this command.
 * The pending slot is **untouched** by this call.
 */
async getVerifyCaptcha() : Promise<Result<VerifyCaptcha, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_verify_captcha") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Submit the verify form with `verify_code` (email / SMS code) and
 * `captcha_code` (typed-out captcha).
 * 
 * # Preconditions
 * 
 * Must be preceded by [`get_verify_page_info`]; otherwise surfaces
 * [`VERIFY_NOT_STARTED_CODE`].
 * 
 * # Behaviour on each outcome
 * 
 * - [`VerifyOutcome::Success`] — pending slot cleared; return
 * [`VerifySubmit::Success`]. Frontend should re-run the
 * original login command.
 * - [`VerifyOutcome::WrongCaptcha`] / [`VerifyOutcome::WrongAuthInfo`] /
 * [`VerifyOutcome::ServerMessage`] — pending slot **retained** so
 * the user can retry without re-fetching the AdvanceCheck page.
 */
async submitVerify(verifyCode: string, captchaCode: string) : Promise<Result<VerifySubmit, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("submit_verify", { verifyCode, captchaCode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Terminate the active Beanfun session and release every
 * backend-held continuation.
 * 
 * # Behaviour
 * 
 * - If [`AppState::auth`] is populated: invoke
 * [`services::beanfun::login::logout`][svc] so the server-side
 * session is invalidated (3 best-effort HTTP calls; see the
 * service-level module docs). Errors are logged via `tracing`
 * but **never surfaced to the frontend** — logout is UX-critical
 * and must not appear to fail.
 * - Clears `auth`, `pending_totp`, `pending_qr`,
 * `pending_verify`, and `pending_gamepass` unconditionally.
 * After this command returns, every subsequent command that
 * calls `require_auth` / reads a pending slot will surface its
 * typed "not started" / "session_required" error.
 * 
 * # Idempotence
 * 
 * Safe to call repeatedly. On a fresh process (every slot already
 * `None`) the command is a no-op that still returns `Ok(())`.
 * 
 * # Why no error surface?
 * 
 * Matches WPF's `App.xaml.cs` L72-76 / `MainWindow.xaml.cs`
 * L237-241 which both wrap `BeanfunClient.Logout()` in
 * `try { } catch { }` — logout is fire-and-forget in the
 * reference implementation. Our cmd layer goes one step further
 * and *guarantees* local cleanup happens regardless of server
 * response.
 * 
 * [svc]: crate::services::beanfun::login::logout()
 */
async logout() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("logout") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List the service accounts the logged-in user can launch into the
 * session's current service + region.
 * 
 * # Returns
 * 
 * An [`AccountListResult`] bundle with:
 * 
 * - `accounts` — sorted by ascending `ssn` (WPF first-pass sort).
 * - `amount_limit_notice` — typed quota-notice classification
 * (`None` / `AuthReLoginRequired` / `Other { message }`).
 * 
 * # Errors
 * 
 * - `auth.session_required` — no login is active.
 * - Every [`LoginError`][le] surfaced by the service-layer
 * `get_accounts` (transport / parse / body-too-large). The
 * P10.1 `From<LoginError>` impl handles mapping verbatim.
 * 
 * # Frontend usage
 * 
 * Called on first render of the account-picker screen. See
 * [`refresh`] for the UI's "reload" affordance.
 * 
 * [le]: crate::services::beanfun::LoginError
 */
async getAccounts() : Promise<Result<AccountListResult, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_accounts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Semantic alias for [`get_accounts`] — re-fetch the account list.
 * 
 * # Why a second command instead of just `get_accounts`?
 * 
 * Two separate commands let the frontend's intent be legible at the
 * call site (`invoke('get_accounts')` on first render vs.
 * `invoke('refresh')` on the reload button) without the backend
 * diverging behaviour. A future requirement (analytics counter,
 * stricter rate limit, cache bypass) can land in one `#[tauri::command]`
 * body without touching the other's contract.
 * 
 * # Implementation
 * 
 * Delegates to the same [`list_accounts_internal`] helper as
 * [`get_accounts`] — both commands are pure wire adapters on top
 * of the single internal primitive, so there is no duplicated
 * flow logic to keep in sync (DRY).
 * 
 * # When to call
 * 
 * On user-initiated "refresh" button clicks, and after commands
 * that invalidate the list (e.g. `add_service_account`,
 * `change_display_name` — both in D9).
 */
async refresh() : Promise<Result<AccountListResult, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add a new service account (character slot) for the logged-in user
 * under the session's current service + region.
 * 
 * # Contract
 * 
 * Mirrors [`services::beanfun::add_service_account`][svc] verbatim:
 * 
 * - Empty `name` → `Ok(false)` *without firing a request* (server
 * roundtrip is redundant — the form validation on the WPF dialog
 * gates the same way, so we preserve both the UI semantic and the
 * zero-network-cost shape).
 * - Non-empty → `POST gamezone.ashx` with
 * `strFunction=AddServiceAccount`; response's `intResult == 1` →
 * `true`, anything else (including empty body or missing field) →
 * `false`.
 * 
 * # Why pull `service_code` / `service_region` from the session?
 * 
 * WPF's `MainWindow.AddServiceAccount` (`Beanfun/MainWindow.xaml.cs`)
 * uses the same globals — the add-account dialog only ever targets
 * the user's current game. Exposing the two fields as IPC parameters
 * would invite the frontend to pass mismatched values (e.g. a stale
 * account-list snapshot from before the region switched), so we lock
 * the source of truth to [`Session`][sesh] on the backend.
 * 
 * # Errors
 * 
 * - `auth.session_required` — no login is active.
 * - Any [`LoginError`][le] surfaced by the service (`auth.aspx`
 * pre-flight / `gamezone.ashx` transport / JSON parse / body-too-
 * large). Already mapped to `CommandError` by the P10.1
 * `From<LoginError>` impl.
 * 
 * # Frontend usage
 * 
 * After a successful return, the caller should invoke [`refresh`]
 * to pick up the new row (gamezone does not echo the account back).
 * 
 * [svc]: crate::services::beanfun::add_service_account
 * [sesh]: crate::services::beanfun::Session
 * [le]: crate::services::beanfun::LoginError
 */
async addServiceAccount(name: string) : Promise<Result<boolean, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_service_account", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rename an existing service account's display name.
 * 
 * # Contract
 * 
 * Mirrors [`services::beanfun::change_service_account_display_name`][svc]
 * verbatim:
 * 
 * - `new_name.is_empty()` **or** `new_name == account.sname` →
 * `Ok(false)` without firing a request (WPF early-out — server
 * would reject identical names anyway, so we skip the roundtrip).
 * - Otherwise → `POST gamezone.ashx` with
 * `strFunction=ChangeServiceAccountDisplayName, sl=<game_code>,
 * said=<account.sid>, nsadn=<new_name>`; response's
 * `intResult == 1` → `true`, anything else → `false`.
 * 
 * # Why echo the whole `ServiceAccount` from the frontend?
 * 
 * The service layer mirrors WPF's signature (which takes the whole
 * `ServiceAccount` so the call site can early-out on
 * `newName == account.sname`). Rather than reshape the service
 * call or build a partially-populated `ServiceAccount` in the
 * command layer (which would require manually updating every time
 * the struct gains a new field), we let the frontend echo the
 * object it already has in hand from [`get_accounts`]. `ServiceAccount`
 * contains only display-oriented public fields (no secrets), so
 * the echo round-trip is safe — which is why it derives
 * `serde::Deserialize` alongside `Serialize + specta::Type`.
 * 
 * # Why pull `game_code` from the session?
 * 
 * `game_code = "{service_code}_{service_region}"` — constructed on
 * the backend to prevent the frontend from drifting the two halves
 * against each other (exactly as [`add_service_account`] locks
 * down the service code / region split).
 * 
 * # Errors
 * 
 * - `auth.session_required` — no login is active.
 * - Any [`LoginError`][le] surfaced by the service.
 * 
 * # Frontend usage
 * 
 * On `Ok(true)`, the caller should update its local `ServiceAccount`
 * (`sname = new_name`) or invoke [`refresh`]. On `Ok(false)` — either
 * the caller passed an invalid / unchanged name (expected UI
 * prevention), or the server rejected the change (show a generic
 * "could not rename" message — mirrors WPF's `MsgChangeDisplayNameError`).
 * 
 * [svc]: crate::services::beanfun::change_service_account_display_name
 * [le]: crate::services::beanfun::LoginError
 */
async changeDisplayName(newName: string, account: ServiceAccount) : Promise<Result<boolean, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_display_name", { newName, account }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch the EULA / service contract HTML for the session's current
 * service + region.
 * 
 * # Contract
 * 
 * Thin wrapper over [`services::beanfun::get_service_contract`][svc].
 * Same `service_code` / `service_region` policy as
 * [`add_service_account`] — pulled from [`Session`][sesh] so the
 * frontend cannot drift the two halves against each other.
 * 
 * Returns the raw HTML fragment the server emits in the
 * `strResult` JSON field (or `""` when `intResult != 1` / the body
 * is empty — matching WPF).
 * 
 * # Errors
 * 
 * - `auth.session_required` — no login is active.
 * - Any [`LoginError`][le] surfaced by the service (transport,
 * JSON parse, body-too-large).
 * 
 * # Frontend usage
 * 
 * The UI renders the returned HTML inside the "service contract"
 * dialog (matching WPF's `Contract.xaml`). We return the body
 * verbatim so the frontend's XSS policy — a dedicated render
 * component with a sanitizer — owns the sanitisation decision;
 * applying a sanitiser here would hard-code one policy for every
 * consumer.
 * 
 * [svc]: crate::services::beanfun::get_service_contract
 * [sesh]: crate::services::beanfun::Session
 * [le]: crate::services::beanfun::LoginError
 */
async getContract() : Promise<Result<string, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_contract") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch the logged-in user's e-mail address.
 * 
 * # Contract
 * 
 * Thin wrapper over [`services::beanfun::get_email`][svc]. TW
 * sessions return the captured address; HK sessions short-circuit
 * to `""` **without** firing a request (the HK portal does not
 * expose this endpoint — mirrors WPF `BeanfunClient.cs::getEmail`
 * L245-246).
 * 
 * Returns the e-mail string, or `""` when the TW regex does not
 * match / the session is HK.
 * 
 * # Errors
 * 
 * - `auth.session_required` — no login is active.
 * - Any [`LoginError`][le] surfaced by the service (transport,
 * body-too-large).
 * 
 * # Frontend usage
 * 
 * The AccountList "view e-mail" affordance hides itself when the
 * return is empty (matches WPF's `AccountList.xaml.cs`
 * `m_GetEmail_Click` behaviour — nothing is shown for empty).
 * 
 * [svc]: crate::services::beanfun::get_email
 * [le]: crate::services::beanfun::LoginError
 */
async getEmail() : Promise<Result<string, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_email") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch the remaining Beanfun points balance.
 * 
 * # Contract
 * 
 * Thin wrapper over [`services::beanfun::get_remain_point`][svc].
 * Returns an `i32` for drop-in parity with WPF's `int` return
 * (`BeanfunClient.cs::getRemainPoint` L214).
 * 
 * Returns `0` when the server response does not match the
 * `"RemainPoint" : "…"` regex **or** the captured value is not a
 * valid `i32` — matches WPF's blanket `catch { return 0; }`.
 * 
 * # Errors
 * 
 * - `auth.session_required` — no login is active.
 * - Any [`LoginError`][le] surfaced by the service. (The WPF
 * `catch` would swallow these as `0`; we propagate so the
 * frontend can distinguish "server rejected" from "network
 * down" — the UI can apply the `→ 0` rule locally if strict
 * WPF parity is desired.)
 * 
 * # Frontend usage
 * 
 * The AccountList header surfaces this as the "剩餘 B$" ticker
 * (matches WPF `AccountList.xaml.cs` L139 → `updateRemainPoint`).
 * 
 * [svc]: crate::services::beanfun::get_remain_point
 * [le]: crate::services::beanfun::LoginError
 */
async getRemainPoint() : Promise<Result<number, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_remain_point") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retrieve the one-time game-launch password for a given service
 * account.
 * 
 * # Contract
 * 
 * Thin wrapper over [`crate::services::beanfun::get_otp`]. The
 * returned string is the 6-character password the Beanfun launcher
 * feeds into `MapleStory.exe` as the second token. On success the
 * UI copies this to the clipboard and displays it in the OTP
 * dialog (matching WPF's `CopyBox.xaml`).
 * 
 * # Why accept the whole `ServiceAccount` instead of `sid`?
 * 
 * [`crate::services::beanfun::get_otp`] takes `&ServiceAccount` because
 * several of the 5 HTTP steps need fields beyond `sid` (e.g.
 * `ssn` for `record_start` body, `screatetime` for the post-WCDES
 * JSON envelope). Reshaping the service call to accept a minimal
 * `{sid, ssn, screatetime}` bundle would leak the protocol shape
 * into the command layer; echoing the full [`ServiceAccount`] the
 * frontend already has from [`commands::account::get_accounts`]
 * is strictly cheaper and preserves the service-layer SRP.
 * 
 * [`ServiceAccount`] has `serde::Deserialize` already (set by D9
 * for [`commands::account::change_display_name`]) — no additional
 * derives needed.
 * 
 * # Errors
 * 
 * - `auth.session_required` — no login is active.
 * - Any [`LoginError`][le] surfaced by the service (transport,
 * JSON parse, WCDES decrypt, server-side intResult ≠ 1). The
 * P10.1 `From<LoginError>` impl maps each variant to its
 * structured `CommandError` shape.
 * 
 * # Frontend usage
 * 
 * Invoked by the AccountList "get OTP" button (matches WPF
 * `AccountList.xaml.cs` `m_GetOTP_Click`). The returned string
 * should be shown in the `CopyBox` dialog and copied to
 * clipboard; do **not** log this value.
 * 
 * [svc]: crate::services::beanfun::get_otp
 * [le]: crate::services::beanfun::LoginError
 * [`ServiceAccount`]: crate::services::beanfun::ServiceAccount
 * [`commands::account::get_accounts`]: crate::commands::account::get_accounts
 * [`commands::account::change_display_name`]: crate::commands::account::change_display_name
 */
async getOtp(account: ServiceAccount) : Promise<Result<string, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_otp", { account }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open `url` in the user's default handler (browser for http/https,
 * mail client for mailto).
 * 
 * Thin wrapper over [`crate::services::system::open_url()`] — the
 * service layer enforces the scheme allowlist (`http` / `https` /
 * `mailto`) and wraps the synchronous [`open::that`] call in
 * [`tokio::task::spawn_blocking`], so this command stays a
 * single-line delegation (P10.3-Q1 = A decision: command layer is
 * strictly the IPC boundary, business logic lives in `services/`).
 * 
 * # Errors
 * 
 * - `system.invalid_url` — URL is empty, missing a scheme, or uses
 * a scheme outside the allowlist. Rejected before any OS call.
 * - `system.open_url_failed` — OS opener (`ShellExecuteW` /
 * `LSOpenCFURLRef` / `xdg-open`) returned an I/O error.
 * - `system.spawn_blocking_failed` — the blocking task hosting
 * [`open::that`] panicked or was cancelled (should not happen in
 * steady state).
 */
async openUrl(url: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_url", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read a single config value by `key`, falling back to `""` when
 * the file is missing / unreadable / the key is absent.
 * 
 * Thin wrapper over [`crate::services::config::get_value`] — the
 * service layer already implements WPF's catch-all semantics,
 * including the `tracing::warn!` on read failure. This command
 * adds only the storage-root path resolution.
 * 
 * # Errors
 * 
 * Despite the `Result<_, CommandError>` signature this command
 * never surfaces an error in practice — the underlying
 * [`crate::services::config::get_value`] is infallible (catch-all
 * policy). The `Result` shape is retained for symmetry with
 * [`get_all_config`] / [`set_config`] and to leave room for future
 * validation (e.g. reject keys containing control characters if
 * that becomes a concern).
 */
async getConfigValue(key: string) : Promise<Result<string, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_config_value", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read every `<add key value />` entry from `Config.xml` as a flat
 * map. Any read / parse failure is swallowed and a warning is
 * logged — the frontend always sees a map (possibly empty) so the
 * settings page never needs to handle a "config corrupted" error
 * state (WPF-parity catch-all for bulk read; see error-policy
 * table in the module docs).
 * 
 * # Ordering
 * 
 * [`IndexMap`][indexmap::IndexMap] preserves insertion order on the
 * service side, but specta serialises `HashMap<String, String>`
 * (this command's return type) as a JSON object. ES2020 object
 * property iteration order is insertion-ordered for string keys,
 * so the ordering survives the IPC boundary on modern runtimes;
 * frontend callers that need a guaranteed order should sort by
 * key client-side regardless.
 * 
 * # Why `HashMap` over `IndexMap`?
 * 
 * `specta::Type` supports both, but `HashMap<String, String>` is
 * the canonical "dictionary" shape the rest of the command layer
 * already uses (e.g. future export-account bundles). Keeping one
 * shape across the IPC boundary avoids forcing the frontend to
 * branch on an ordered-vs-unordered distinction that is only
 * meaningful server-side.
 */
async getAllConfig() : Promise<Result<Partial<{ [key in string]: string }>, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_all_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set, update, or remove a config entry.
 * 
 * - `value = Some(v)` → upsert (in-place for existing keys,
 * append for new ones — matches .NET `Settings[k].Value = v` /
 * `Settings.Add(k, v)` distinction without a branch).
 * - `value = None` → remove (no-op when the key is already
 * absent; preserves the rest of the map's order).
 * 
 * # Error surface (deviation from WPF)
 * 
 * Unlike [`get_config_value`] / [`get_all_config`] (catch-all),
 * this command propagates the service-layer typed errors
 * ([`crate::services::config::ConfigError::Io`] /
 * [`crate::services::config::ConfigError::XmlWrite`]) so the UI
 * can tell the user when their setting didn't persist. WPF
 * swallows these silently at
 * `ConfigAppSettings.cs` L60 which caused user-visible settings
 * loss without any indication; the Rust port surfaces them as
 * `config.io_failed` / `config.xml_write_failed` codes for the
 * frontend to handle explicitly.
 */
async setConfig(key: string, value: string | null) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_config", { key, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Decrypt `Users.dat` and return every saved account as a row-
 * shaped [`Account`] list.
 * 
 * First-time boot (file missing) returns an empty list — WPF
 * behaviour. Legacy P6 NRBF files are auto-migrated to the new
 * JSON format via
 * [`crate::services::storage::load_records_with_legacy_migration`]
 * before the decrypted rows are returned.
 * 
 * # Errors
 * 
 * - `storage.dpapi_failed` / `storage.io_failed` / `storage.json_failed` /
 * `storage.entropy_missing` / `storage.entropy_shape` — see
 * [`crate::services::storage::StorageError`] for each cause.
 * - `storage.platform_unsupported` — non-Windows build.
 */
async loadAccounts() : Promise<Result<Account[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_accounts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Upsert a single `account` into `Users.dat`, matched by
 * `(region, account_id)`. Returns the full updated list so the
 * frontend can refresh without another round-trip.
 * 
 * See module docs for the Q7 = A plaintext-password policy that
 * governs `account.password`.
 * 
 * # Errors
 * 
 * - `storage.*` — DPAPI / IO / registry surface from
 * [`crate::services::storage::StorageError`].
 * - `storage.platform_unsupported` — non-Windows build.
 */
async saveAccount(account: Account) : Promise<Result<Account[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_account", { account }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete the row matching `(region, account_id)` from `Users.dat`.
 * No-op (not an error) when the row is absent. Returns the full
 * updated list so the frontend can refresh in one round-trip.
 * 
 * # Errors
 * 
 * - `storage.*` — DPAPI / IO / registry surface from
 * [`crate::services::storage::StorageError`].
 * - `storage.platform_unsupported` — non-Windows build.
 */
async removeAccount(region: string, accountId: string) : Promise<Result<Account[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_account", { region, accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read an external plaintext JSON file at `path` and overwrite
 * `Users.dat` with its contents (re-encrypted under a fresh
 * DPAPI entropy). Matches WPF `importRecord` — the JSON format is
 * the WPF parallel-columns wire shape, byte-for-byte compatible
 * with files exported by either the legacy client or
 * [`export_records`].
 * 
 * Returns the newly-persisted account list (same shape as
 * [`load_accounts`]).
 * 
 * # Errors
 * 
 * - `storage.import_read_failed` — external file I/O failure
 * (file missing, permission denied, …). Details include `path`
 * and `io_kind`.
 * - `storage.json_failed` — the external file is not valid
 * `WireRecords` JSON.
 * - `storage.*` (DPAPI / registry / IO) — failure during the
 * re-encrypt + overwrite step against `Users.dat`.
 * - `storage.platform_unsupported` — non-Windows build.
 */
async importRecords(path: string) : Promise<Result<Account[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_records", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Serialise the current `Users.dat` contents as the WPF parallel-
 * columns JSON wire format and write to `path` (external file).
 * Matches WPF `exportRecord`.
 * 
 * **Plaintext password caveat:** the output file includes every
 * account password in clear text (Q7 = A policy — module docs
 * spell out the rationale). Treat the resulting file as a
 * password backup.
 * 
 * # Errors
 * 
 * - `storage.*` (DPAPI / registry / IO) — failure during the
 * `Users.dat` decrypt step.
 * - `storage.export_write_failed` — external file I/O failure
 * while writing to `path`. Details include `path` and `io_kind`.
 * - `storage.platform_unsupported` — non-Windows build.
 */
async exportRecords(path: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_records", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check whether a newer Beanfun release is available on the
 * upstream GitHub releases feed.
 * 
 * Returns `Some(UpdateInfo)` when a newer release was found,
 * `None` for "no update available" or "check failed" (indistinguishable
 * to the caller — this is intentional, matching WPF's silent-on-
 * failure contract so the UI never shows an error for a passive
 * background check).
 * 
 * # Parameters
 * 
 * - `channel` — `Stable` to filter out prereleases, `Beta` to
 * accept them (matches the WPF `updateChannel` config value).
 * Frontend settings pages can bind to a single string
 * (`"Stable"` / `"Beta"`) thanks to `Channel`'s `Serialize`
 * derive using unit-variant form.
 * - `local_version` — optional override. When `None` the backend
 * self-reports `env!("CARGO_PKG_VERSION")`.
 * 
 * # Background-refresh caching
 * 
 * The service layer caches the proxy probe result in an
 * `OnceLock`, so repeated calls within a single process pay the
 * HEAD-probe cost only once. The command does not re-probe; if a
 * forced re-probe ever becomes necessary (e.g. after a network
 * reconfiguration), [`crate::services::updater::check_update_at`]
 * is the escape hatch — exposing that through the command surface
 * is YAGNI until a user-visible feature requests it.
 */
async checkUpdate(channel: Channel, localVersion: string | null) : Promise<UpdateInfo | null> {
    return await TAURI_INVOKE("check_update", { channel, localVersion });
},
/**
 * Launch the configured game binary with the current account
 * credentials.
 * 
 * Thin wrapper over [`crate::services::game::launch_game`] — see the
 * module-level docs for the full rationale, credential-handling
 * policy, and blocking-isolation contract. The command performs
 * three orchestration steps before delegating:
 * 
 * 1. Resolve the LocaleRemulator staging directory via
 * [`default_target_dir`]. Fails with
 * `launcher.target_dir_resolve_failed` if `current_exe()` or
 * its `.parent()` is unavailable (extremely rare — only
 * happens when the main binary has been deleted while
 * running).
 * 2. Assemble the command-line string via [`build_command_line`]
 * (see that helper's docs for the empty-string short-circuit
 * semantics).
 * 3. Hand the [`LaunchRequest`] to the service orchestrator under
 * [`tokio::task::spawn_blocking`]. A [`tokio::task::JoinError`]
 * surfaces as `launcher.spawn_blocking_failed`; any
 * [`crate::services::game::GameError`] from the orchestrator
 * itself (path validation / LR resource release / ShellExecute
 * / Command::spawn) flows through the existing
 * [`From<GameError> for CommandError`][gfrom] conversion.
 * 
 * # Parameters
 * 
 * - `game_path` — absolute path to the game executable (e.g.
 * `C:\\Games\\MapleStory\\MapleStory.exe`). Frontend typically
 * reads this from `Config.xml` via `get_config_value` — this
 * command does not read Config itself (SRP).
 * - `mode` — user's requested launch mode. `Auto` will resolve
 * against the Windows system locale inside the service layer;
 * see [`crate::services::game::resolve_mode`]. Maps to the
 * legacy `startGameMode` integer config value on the frontend
 * side.
 * - `command_line_template` — per-game command-line template with
 * `%s` placeholders. Empty string disables credential
 * substitution entirely (the game is launched with no
 * arguments). Typically sourced from the per-game INI pipeline
 * that P11/P12 will implement.
 * - `account` / `password` — the logged-in game account
 * credentials. Both empty → no substitution (see
 * [`build_command_line`]). Plaintext over IPC by P10.3 Q7=A
 * decision; treat this command as sensitive at the callsite.
 * 
 * # Fire-and-forget
 * 
 * The spawned game process is detached — the service layer drops
 * the `std::process::Child` immediately on Normal mode, and
 * `ShellExecuteW` takes care of its own child on LR mode. There
 * is no `pid` returned, no lifecycle tracking: matches the legacy
 * WPF behaviour (P10.3 Q5 = A "stateless process commands").
 * 
 * [gfrom]: crate::commands::error#gameerror--commanderror-servicesgame
 */
async launchGame(gamePath: string, mode: GameStartMode, commandLineTemplate: string, account: string, password: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("launch_game", { gamePath, mode, commandLineTemplate, account, password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persist the user-chosen game install path for `game_code` into
 * `Config.xml`.
 * 
 * Thin wrapper over [`crate::services::config::set_value`] —
 * see the D5b section in the module docs for the Config key format
 * and the rationale for keeping `dir_value_name` / `game_code` as
 * explicit parameters (INI separation).
 * 
 * # Parameters
 * 
 * - `game_code` — composite key the settings page supplies (e.g.
 * `"610074_T9"`, from `service_code + "_" + service_region`).
 * - `dir_value_name` — INI-sourced column name (e.g. `"ExecPath"`);
 * becomes the prefix of the Config.xml key.
 * - `path` — the chosen executable-dir path. Empty string is
 * accepted and written verbatim; callers that want to *remove*
 * the entry entirely should use
 * [`crate::commands::config::set_config`] with `value = None`.
 * 
 * # Errors
 * 
 * - `config.io_failed` / `config.xml_write_failed` — see
 * [`crate::services::config::ConfigError`] for the full surface.
 * 
 * # Platform
 * 
 * Unconditional — Config I/O is portable. Only
 * [`detect_game_path`] requires Windows (registry lookup).
 */
async setGamePath(gameCode: string, dirValueName: string, path: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_game_path", { gameCode, dirValueName, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resolve the install path for `game_code`, consulting
 * `Config.xml` first and falling back to the Windows registry.
 * Writes any freshly-discovered registry value back to Config so
 * future calls are fast (WPF parity — see L574-607).
 * 
 * Returns:
 * - `Ok(Some(path))` — Config already had a value **or** the
 * registry supplied one (in which case Config is now updated).
 * - `Ok(None)` — both Config and the registry came up empty (or
 * `dir_reg` was an empty string, meaning the INI has no fallback
 * key configured). WPF shows an empty `t_GamePath` textbox in
 * this case; this shape lets the frontend render the same way
 * without another round-trip.
 * 
 * # Parameters
 * 
 * - `game_code` — composite identifier (`service_code_region`).
 * - `dir_value_name` — INI-sourced Config column name and
 * registry `REG_SZ` value name (WPF reuses the same string for
 * both, L574 / L587).
 * - `dir_reg` — INI-sourced registry subkey path. May contain a
 * leading `HKEY_LOCAL_MACHINE\` literal which is stripped
 * verbatim before the HKCU lookup (WPF L580 parity; see module
 * docs for why only HKLM).
 * 
 * # Errors
 * 
 * - `config.io_failed` / `config.xml_write_failed` — the Config
 * write-back step failed after a successful registry read.
 * - `registry.open_key_failed` / `registry.read_value_failed` —
 * the registry lookup surfaced a non-NotFound IO error (e.g.
 * permission denied). NotFound / empty value / missing subkey
 * are **not** errors — they fold into `Ok(None)` per WPF's
 * silent fallback at L596-599.
 * - `launcher.spawn_blocking_failed` — the registry-read
 * `spawn_blocking` task panicked or was cancelled.
 * - `launcher.platform_unsupported` — non-Windows build.
 */
async detectGamePath(gameCode: string, dirValueName: string, dirReg: string) : Promise<Result<string | null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detect_game_path", { gameCode, dirValueName, dirReg }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Enumerate every running process whose executable path byte-equals
 * `game_path`.
 * 
 * Thin wrapper over
 * [`crate::services::process::game::find_game_processes`] — see the
 * D5c section in the module docs for the WPF parity contract and the
 * IPC DTO rationale. The returned [`GameProcessInfo`] list is empty
 * when nothing matches (not an error).
 * 
 * # Parameters
 * 
 * - `game_path` — absolute path to the game executable. Typically
 * the same value the frontend later passes to [`launch_game`];
 * the match is byte-exact against `Win32_Process.ExecutablePath`,
 * so "same exe name under a different install directory" is
 * deliberately treated as a different game (e.g. two MapleStory
 * installs don't interfere).
 * 
 * # Fire-pattern
 * 
 * Designed to be called **before** [`launch_game`] so the UI can
 * prompt the user to close existing instances first. The frontend
 * then forwards any pids the user confirmed into
 * [`kill_game_processes`]. The separation (list vs kill) keeps the
 * confirm dialog on the Vue side and lets the backend stay
 * stateless (P10.3 Q4 = A).
 * 
 * # Errors
 * 
 * - `process.wmi_init_failed` / `process.wmi_connect_failed` /
 * `process.wmi_query_failed` — from the underlying WMI round-trip,
 * via [`From<ProcessError> for CommandError`][pfrom].
 * - `launcher.spawn_blocking_failed` — the `spawn_blocking` task
 * panicked or was cancelled.
 * - `launcher.platform_unsupported` — non-Windows build target.
 * 
 * [pfrom]: crate::commands::error#processerror--commanderror-servicesprocess
 */
async listGameProcesses(gamePath: string) : Promise<Result<GameProcessInfo[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_game_processes", { gamePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Best-effort terminate every pid in `pids`, returning the subset
 * that was actually killed.
 * 
 * Thin wrapper over
 * [`crate::services::process::game::kill_game_processes`] — see the
 * D5c section in the module docs for the best-effort semantics and
 * the frontend trust-boundary rationale.
 * 
 * # Parameters
 * 
 * - `pids` — the pids to terminate. **Not re-validated** against
 * any game path; the frontend is expected to have just called
 * [`list_game_processes`] and obtained explicit user consent
 * before forwarding the pids here. This matches the WPF
 * inline "Yes" branch at `MainWindow.xaml.cs` L1821-1833 which
 * kills from the list it just computed without a second
 * validation pass.
 * 
 * # Returns
 * 
 * `Vec<u32>` of pids that were successfully terminated, in input
 * order. Per-pid failures (process exited mid-kill, permission
 * denied, protected process) are silently skipped — callers that
 * need to surface leftovers should re-invoke [`list_game_processes`]
 * and diff. An empty input produces an empty output without any
 * `OpenProcess`/`TerminateProcess` calls.
 * 
 * # Errors
 * 
 * - `launcher.spawn_blocking_failed` — the `spawn_blocking` task
 * panicked or was cancelled. No `process.*` errors surface here
 * because the service-layer primitive swallows per-pid failures
 * by design.
 * - `launcher.platform_unsupported` — non-Windows build target.
 */
async killGameProcesses(pids: number[]) : Promise<Result<number[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("kill_game_processes", { pids }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Type the account name + OTP into the MapleStory launcher's
 * login dialog and press Enter, replicating the tail of
 * `getOtpWorker_RunWorkerCompleted`
 * (`Beanfun/MainWindow.xaml.cs` L2158-2238).
 * 
 * Thin wrapper over
 * [`crate::services::process::auto_paste::paste_credentials`] —
 * see the D5d section in the module docs for the full design
 * breakdown, DTO rationale, and `specialClick` dispatch contract.
 * 
 * # Parameters (shape pinned by [`AutoPasteRequest`])
 * 
 * - `className` — launcher window class to target; the
 * `MapleStoryClassTW` fallback is applied automatically when
 * `className == "MapleStoryClass"`.
 * - `account` / `password` — credentials to type. Both must be
 * ASCII; non-ASCII surfaces as `process.non_ascii`.
 * - `specialClick` — run the SEA pre-login dismiss + click
 * pipeline (`true` on MapleStory SEA / TW, `false` elsewhere).
 * 
 * # Fire pattern
 * 
 * Frontend typically calls this **after** successfully retrieving
 * the OTP for the selected account, and **after** the user has
 * either let the auto-launch happen or opened the launcher dialog
 * manually. On a `process.window_not_found` response, the UI is
 * expected to fall back to clipboard-copying the OTP (mirrors
 * WPF L2169-2174).
 * 
 * # Errors
 * 
 * - `process.window_not_found` — no launcher window of the given
 * class exists. Frontend should copy the password to clipboard
 * and surface the OTP for manual paste.
 * - `process.post_message_failed` / `process.win32_call_failed` —
 * the target window went away mid-paste.
 * - `process.non_ascii` — `account` or `password` contains a
 * non-ASCII codepoint; WPF silently replaces with `'?'`
 * (corrupting credentials), the Rust port refuses loudly.
 * - `launcher.spawn_blocking_failed` — the `spawn_blocking` task
 * panicked or was cancelled.
 * - `launcher.platform_unsupported` — non-Windows build.
 */
async autoPaste(req: AutoPasteRequest) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auto_paste", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * One persisted account row. Mirrors the i-th element across WPF
 * `Records`'s seven parallel `List<...>` fields
 * (`Beanfun/Helper/AccountManager.cs` L34-43).
 * 
 * `region` defaults to `"TW"` and `method` to `0` to match the WPF
 * `accRecInit` defaults; everything else defaults to its type's
 * natural zero value.
 * 
 * # IPC exposure (P10.3 Q7 = A — plaintext passthrough)
 * 
 * Derives [`serde::Serialize`] + [`serde::Deserialize`] +
 * [`specta::Type`] so the P10.3 storage commands can hand row-
 * shaped account objects across the IPC boundary verbatim.
 * `password` crosses the boundary **in plaintext** — matches WPF
 * which returns the decrypted password to the UI for auto-fill /
 * launch flows, and the webview shares the app's trust boundary
 * (same Windows user session, same process tree). Import / export
 * JSON files likewise contain plaintext (see
 * [`crate::services::storage::export_records`] / [`import_records`]
 * module docs for the on-disk JSON caveats).
 */
export type Account = { 
/**
 * e.g. `"TW"` / `"HK"`. Defaults to `"TW"` per WPF `accRecInit`.
 */
region: string; 
/**
 * Login account / member ID — `accountList[i]` in WPF.
 */
account_id: string; 
/**
 * User-assigned display name — `accountNameList[i]` in WPF.
 */
account_name: string; 
/**
 * Saved password — `passwdList[i]` in WPF.
 */
password: string; 
/**
 * Verify token (HK-only) — `verifyList[i]` in WPF.
 */
verify: string; 
/**
 * Login method enum value (id/pass / QR / GamePass / TOTP) —
 * `methodList[i]` in WPF; defaults to `0`.
 */
method: number; 
/**
 * Auto-login flag — `autoLoginList[i]` in WPF; defaults to false.
 */
auto_login: boolean }
/**
 * Result of [`get_accounts`]: the sorted account list plus the optional
 * quota notice.
 */
export type AccountListResult = { 
/**
 * Service accounts sorted by ascending `ssn` (WPF
 * `accountList.Sort((x, y) => x.ssn.CompareTo(y.ssn))`). Callers
 * that want a different order — e.g. user-defined drag-and-drop
 * from persistent storage — should layer that transformation on
 * top.
 */
accounts: ServiceAccount[]; 
/**
 * Server-side quota notice, classified into a typed
 * [`AmountLimitNotice`] so callers can dispatch without string
 * comparisons.
 */
amount_limit_notice: AmountLimitNotice }
/**
 * Server-side notice shown when the user has hit the account quota.
 * 
 * WPF stuffs the localised text directly into a UI string (`I18n.ToSimplified`
 * / `TryFindResource("AuthReLogin")`). We keep the service layer i18n-free
 * and let the UI choose what to render.
 */
export type AmountLimitNotice = 
/**
 * No `divServiceAccountAmountLimitNotice` element on the page.
 */
{ kind: "none" } | 
/**
 * The notice contained the substring `"進階認證"` — WPF treats this
 * as a sentinel for "user must complete advance verification before
 * they can add more accounts" and shows a fixed `AuthReLogin`
 * resource string. Carries no payload because the original text is
 * irrelevant once classified.
 */
{ kind: "auth_re_login_required" } | 
/**
 * Any other notice text. Carries the raw, **Traditional Chinese**
 * string verbatim from the server — the UI layer may run it through
 * a simplified-Chinese converter for HK users (matching WPF
 * `I18n.ToSimplified`) or display as-is.
 */
{ kind: "other"; data: string }
/**
 * IPC-shaped input for [`auto_paste`].
 * 
 * Groups the four per-call parameters (window class, account,
 * password, SEA pre-click toggle) into one struct so the frontend
 * spells each field by name — see the D5d section in the module
 * docs for the rationale.
 * 
 * # Field semantics
 * 
 * | Field          | WPF origin                                                    |
 * | -------------- | ------------------------------------------------------------- |
 * | `class_name`   | `MainWindow.win_class_name` (L76, per-game INI column)        |
 * | `account`      | `bfClient.accountList[index].sid` (L2149)                     |
 * | `password`     | `MainWindow.otp` (fresh OTP from `services/beanfun`, L2150)   |
 * | `special_click`| `"610074".Equals(service_code) && "T9".Equals(service_region)` (L2195) |
 * 
 * The fallback to `MapleStoryClassTW` (WPF L2161) is **hardcoded**
 * inside [`crate::services::process::auto_paste`] — frontends
 * that pass `className = "MapleStoryClass"` get the fallback for
 * free; other class names go through without fallback (matches
 * WPF's `"MapleStoryClass".Equals(win_class_name)` guard).
 */
export type AutoPasteRequest = { 
/**
 * Top-level window class name of the launcher dialog
 * (e.g. `"MapleStoryClass"`, `"NexonGameClass"`). Sourced
 * from the per-game INI on the frontend side.
 */
className: string; 
/**
 * Game account name to type into the login dialog. Must be
 * ASCII — non-ASCII bytes surface as `process.non_ascii`
 * (the existing Q3 contract from
 * [`crate::services::process::post_string::post_string`]).
 */
account: string; 
/**
 * Password (or OTP) to type into the password field. Same
 * ASCII constraint as [`Self::account`].
 */
password: string; 
/**
 * When `true`, inject the MapleStory-SEA pre-click sequence
 * (ESC + synthetic click at ~50% / 40% of the client area)
 * before typing credentials. WPF gates this on
 * `service_code == "610074" && service_region == "T9"` —
 * the command layer delegates the decision to the frontend
 * (see module docs).
 */
specialClick: boolean }
/**
 * Which release channel the user is subscribed to.
 * 
 * Mirrors WPF `updateChannel` config value. Binary rather than
 * three-state because `"Preview"` (WPF) aliases `"Beta"` via L204 —
 * the distinction never reached the selection logic, so preserving
 * it here would be noise.
 * 
 * # IPC exposure (P10.3 D4)
 * 
 * Derives [`serde::Serialize`] + [`serde::Deserialize`] +
 * [`specta::Type`] so the `check_update` Tauri command can accept
 * the channel choice from the frontend without a DTO wrapper.
 * Unit variants serialize as plain JSON strings (`"Stable"` /
 * `"Beta"`), matching the WPF `updateChannel` config value shape
 * so settings pages can bind to a single string without a decoder.
 */
export type Channel = 
/**
 * Stable-only: skip releases with `prerelease == true`.
 */
"Stable" | 
/**
 * Prerelease-inclusive: return whichever release is newest,
 * draft or not. Matches WPF `"Beta"` and `"Preview"` both.
 */
"Beta"
/**
 * IPC-facing error DTO. Preserves a stable `{ code, message, details }`
 * shape across every Tauri command.
 * 
 * # Serialization contract
 * 
 * Always serialized as a JSON object with exactly three keys:
 * `code` (string), `message` (string), `details` (nullable JSON value).
 * Frontend types live in
 * `beanfun-next/src/types/bindings.ts` and are auto-generated by
 * `tauri-specta` (P10 chunk 10.1 D8).
 * 
 * # Construction
 * 
 * Use [`CommandError::new`] for the minimum required pair and chain
 * [`CommandError::with_details`] when the domain has extra structured
 * context worth exposing to the UI.
 * 
 * # Display / Error
 * 
 * [`Display`][std::fmt::Display] formats as `[code] message` for
 * `tracing` logs; the type also implements [`std::error::Error`] so
 * it composes with existing `?` / `anyhow` call sites if a command
 * needs to chain through additional fallible ops before surfacing.
 */
export type CommandError = { 
/**
 * Stable `<domain>.<variant_snake_case>` identifier — see
 * [module-level docs](self#code-naming) for the full mapping table.
 */
code: string; 
/**
 * Human-readable, non-localized Rust-side description sourced from
 * the domain error's `Display` impl. Safe to
 * `tracing::error!(%err)`; never contains secrets — the domain
 * layer is responsible for redaction (see P8.2 R8.2-1
 * `LaunchRequest` as the template).
 */
message: string; 
/**
 * Optional structured context — the domain may attach any
 * JSON-representable payload (flat objects preferred). The
 * frontend treats this field as `unknown`-shaped and branches on
 * `code` before reading fields.
 */
details: JsonValue | null }
/**
 * IPC-shaped summary of a running game process, returned by
 * [`list_game_processes`].
 * 
 * # Cross-platform availability
 * 
 * This type is defined at the command layer (not re-exported from
 * [`crate::services::process`]) because the service-layer
 * [`ProcessInfo`][svc_pi] lives inside a
 * `#[cfg(target_os = "windows")]`-gated module. Surfacing the
 * DTO here lets [`list_game_processes`] keep a cross-platform
 * signature (the body errors out at runtime on non-Windows via
 * [`PLATFORM_UNSUPPORTED_CODE`]) so `cargo check` on macOS /
 * Linux dev boxes still produces a stable `bindings.ts`.
 * 
 * # Field semantics
 * 
 * | Field             | Matches                                                    |
 * | ----------------- | ---------------------------------------------------------- |
 * | `pid`             | `Win32_Process.ProcessId` (OS-level pid, stable for life)  |
 * | `name`            | `Win32_Process.Name` (executable file name **with** ext)   |
 * | `executable_path` | `Win32_Process.ExecutablePath` — see **path encoding** below |
 * 
 * ## Path encoding
 * 
 * `executable_path: Option<String>` is the UTF-8 form of the
 * service-layer `Option<PathBuf>`, produced via
 * [`std::path::Path::to_string_lossy`]. Windows paths that land
 * in `Win32_Process.ExecutablePath` are effectively always valid
 * Unicode (the filesystem stores them as UTF-16 and WMI hands us
 * the `String` form directly), so the `to_string_lossy` bridge
 * is lossless in practice. `None` when WMI returned `NULL` (the
 * process is protected or was mid-exit during enumeration).
 * 
 * [svc_pi]: crate::services::process::ProcessInfo
 */
export type GameProcessInfo = { 
/**
 * OS-level process id, stable for the process's lifetime.
 */
pid: number; 
/**
 * Executable file name **including** the `.exe` extension
 * (e.g. `"MapleStory.exe"`).
 */
name: string; 
/**
 * UTF-8 path to the executable on disk, or `None` when WMI
 * couldn't read it (protected process or mid-exit). See the
 * struct-level "Path encoding" section for the conversion
 * rationale.
 */
executablePath: string | null }
/**
 * User-selected launch mode, mirroring WPF `enum GameStartMode`
 * (`Beanfun/MainWindow.xaml.cs` L32-37).
 * 
 * The integer repr matches WPF so a config file saved by the
 * legacy launcher deserialises cleanly into the new enum via
 * [`GameStartMode::try_from`].
 * 
 * # IPC exposure (P10.3 D5a)
 * 
 * Derives [`serde::Serialize`] + [`serde::Deserialize`] +
 * [`specta::Type`] so the `launch_game` Tauri command can accept
 * the mode choice from the frontend without a DTO wrapper. Unit
 * variants serialize as plain JSON strings (`"Auto"` / `"Normal"`
 * / `"LocaleRemulator"`) — the frontend reads the legacy
 * `startGameMode` integer (`"0"` / `"1"` / `"2"`) from Config and
 * maps it to the enum on its side, mirroring the clamp rules in
 * [`GameStartMode::try_from`] (negative = `Auto` fallback, `>= 2`
 * = `LocaleRemulator`). Matches the
 * [`crate::services::updater::Channel`] pattern used by
 * `check_update` (P10.3 D4) for a uniform unit-enum IPC contract.
 */
export type GameStartMode = 
/**
 * Decide `Normal` vs `LocaleRemulator` based on the current
 * system default locale — the default config value.
 */
"Auto" | 
/**
 * Directly `Process.Start` the game binary with its
 * working directory set to the containing folder. Used on
 * Traditional-Chinese locales where the game runs fine in
 * native codepage.
 */
"Normal" | 
/**
 * Launch via `LRProc.exe` (bundled LocaleRemulator) so the
 * game sees a Traditional-Chinese locale regardless of the
 * system default. Used on non-TC systems where the game's
 * ANSI/CP950 code path blows up under the native locale.
 */
"LocaleRemulator"
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * Which region the login flow targets.
 * 
 * Cookies, portal URL, login host and even some response shapes differ
 * between the TW and HK endpoints, so the region is a first-class part of
 * the client configuration rather than a runtime flag on individual
 * calls.
 * 
 * # IPC exposure (P10.2 Q4=C hybrid — data-only path)
 * 
 * This enum is pure data (no secrets, no resources) so it rides the
 * Q4=A path: a [`serde::Serialize`] / [`serde::Deserialize`] /
 * [`specta::Type`] derive applied here lets the command layer
 * reference [`LoginRegion`] directly in DTOs (e.g.
 * `commands::dto::SessionInfo`) without needing a shadow type.
 * 
 * Serde represents the variants as their unit names — the frontend
 * sees a `"TW" | "HK"` union type.
 */
export type LoginRegion = 
/**
 * Taiwan — `tw.beanfun.com` portal, `login.beanfun.com` login host.
 */
"TW" | 
/**
 * Hong Kong — `bfweb.hk.beanfun.com` portal, `login.hk.beanfun.com`
 * login host.
 */
"HK"
/**
 * The safe-subset DTO returned by [`login_qr_start`] — everything
 * the frontend needs to render a QR scanner UI, and nothing more.
 * 
 * # What's inside
 * 
 * - `bitmap_base64` — the full `data:image/png;base64,<…>` data
 * URL. Drops straight into an `<img :src="bitmap_base64">`.
 * - `deeplink` — optional Beanfun-app deeplink the user can tap on
 * mobile instead of scanning.
 * 
 * # What's **NOT** inside
 * 
 * - `skey` (portal session key) — a backend-only secret.
 * - `verification_token` (antiforgery token) — also backend-only;
 * [`login_qr_check`] replays it from [`PendingQr`] directly.
 * 
 * Keeping both secrets backend-side means a hostile (or buggy)
 * frontend cannot forge poll / finalize requests bypassing the
 * command handlers. Mirrors the [`TotpChallenge`][tc] →
 * [`TotpChallengeInfo`] split.
 * 
 * [tc]: crate::services::beanfun::login::TotpChallenge
 */
export type QrStart = { 
/**
 * `data:image/png;base64,...` data URL — preserves WPF's exact
 * storage shape (`bitmapBase64 = "data:image/png;base64," +
 * base64`, `BeanfunClient.Login.cs` L449).
 */
bitmap_base64: string; 
/**
 * Normalised Beanfun-app deeplink, or `None` if the server did
 * not provide one.
 */
deeplink: string | null }
/**
 * Poll result for [`login_qr_check`].
 * 
 * Internally-tagged serde enum — JSON shapes:
 * 
 * ```json
 * { "status": "pending" }
 * { "status": "retry" }
 * { "status": "expired" }
 * { "status": "approved", "session": {...SessionInfo...} }
 * ```
 * 
 * The Vue poll loop is expected to pattern-match on `status`:
 * 
 * - `pending` — user has not yet confirmed in the mobile app;
 * keep polling on the next tick.
 * - `retry` — server reported a round-trip failure but the
 * challenge is still live; keep polling. Mirrors WPF's
 * `ResultMessage == "Failed"` branch (which kept the timer
 * running).
 * - `expired` — QR token aged out; the backend has already
 * cleared [`PendingQr`]. Frontend should call [`login_qr_start`]
 * again to refresh the QR (WPF UI does the same at
 * `MainWindow.qrCheckLogin_Tick` L2364-2367 →
 * `refreshQRCode()`).
 * - `approved` — user confirmed the scan in the mobile app;
 * `login_qr_check` internally ran
 * [`finalize_qr_login`] + set [`AppState::auth`], so the returned
 * `session` is already live.
 * 
 * [`finalize_qr_login`]: crate::services::beanfun::login::finalize_qr_login
 */
export type QrStatus = 
/**
 * `ResultMessage == "Wait Login"` — user hasn't scanned yet.
 */
{ status: "pending" } | 
/**
 * `ResultMessage == "Failed"` — transient round-trip failure;
 * keep polling.
 */
{ status: "retry" } | 
/**
 * `ResultMessage == "Token Expired"` — challenge consumed;
 * backend has already cleared the pending slot.
 */
{ status: "expired" } | 
/**
 * `ResultMessage == "Success"` — scan confirmed; the backend
 * finalised the login and the session is now live.
 */
{ status: "approved"; session: SessionInfo }
/**
 * One row from the user's service-account list, plus the few extra
 * fields WPF carries on the equivalent C# class.
 * 
 * Field names mirror the legacy `BeanfunClient.ServiceAccount` C# class
 * verbatim (`sid` / `ssn` / `sname` / `screatetime` / …) so grep-replace
 * from the old code base lands cleanly. The `Option` types reflect WPF's
 * nullable `string` fields (the constructor used inside `GetAccounts`
 * leaves `slastusedtime` / `sauthtype` `null`, and `screatetime` becomes
 * `null` whenever the per-row `GetCreateTime` HTTP call fails).
 */
export type ServiceAccount = { 
/**
 * `true` when the row's anchor has a non-empty `onclick` handler
 * (WPF: `match.Groups[1].Value != ""`). Disabled accounts still
 * show in the UI but cannot be launched.
 */
is_enable: boolean; 
/**
 * WPF default `true`. Always set by [`get_accounts`] today; the
 * field exists for parity with WPF's two-arg constructor used
 * elsewhere in the legacy code base.
 */
visible: boolean; 
/**
 * WPF default `false`. As above.
 */
is_inherited: boolean; 
/**
 * Service-account id (the `<div id="…">` inner attribute).
 */
sid: string; 
/**
 * Numeric serial number (`sn="…"`).
 */
ssn: string; 
/**
 * Display name (`name="…"`) with HTML entities decoded by the
 * underlying [`extract_service_accounts`] parser
 * (matches WPF `WebUtility.HtmlDecode`).
 */
sname: string; 
/**
 * Server-side creation timestamp scraped from the per-account
 * `game_start_step2.aspx` page. `None` when the scrape fails — WPF
 * returns `null` in that case (`GetCreateTime`'s `catch` block) and
 * the OTP flow tolerates `null` here (it re-fetches if needed).
 */
screatetime: string | null; 
/**
 * WPF default `null` — never populated by `GetAccounts`.
 * Reserved for future flows that bring it in (e.g. `last_used_at`
 * from a separate management endpoint).
 */
slastusedtime: string | null; 
/**
 * WPF default `null` — never populated by `GetAccounts`.
 */
sauthtype: string | null }
/**
 * Public-safe snapshot of an authenticated [`Session`], suitable for
 * exposure over IPC.
 * 
 * # What's inside
 * 
 * - `region` — which Beanfun region the session authenticates against.
 * - `account_id` — the user-facing login id (same thing that appears
 * on the invoice / support ticket).
 * - `service_code` / `service_region` — the MapleStory service this
 * session defaults to launching (`"610074"` / `"T9"` for TW & HK;
 * WPF parity).
 * 
 * # What's **NOT** inside
 * 
 * - `skey` — one-time session key. Held only in the backend.
 * - `web_token` (`bfWebToken` cookie value) — leaking this is
 * equivalent to leaking the session. Held only in the backend (in
 * the cookie jar owned by
 * [`BeanfunClient`][crate::services::beanfun::client::BeanfunClient]).
 * 
 * The frontend never needs these two values because every Beanfun
 * call happens through the backend command layer, which already
 * carries the session via [`AppState`][crate::commands::state::AppState].
 * Not exposing them is a defence-in-depth measure: even if a future
 * renderer-side XSS leaked `localStorage` or a Tauri IPC response
 * log, the session secrets would remain inside the main process.
 */
export type SessionInfo = { 
/**
 * Beanfun region (`TW` / `HK`) — see [`LoginRegion`].
 */
region: LoginRegion; 
/**
 * Login account id. Non-secret.
 */
account_id: string; 
/**
 * MapleStory service code (`"610074"` for both TW and HK in the
 * WPF reference).
 */
service_code: string; 
/**
 * MapleStory service region (`"T9"` for both TW and HK in the
 * WPF reference).
 */
service_region: string }
/**
 * Result of a successful update check where a newer release was found.
 * 
 * UI callers render this directly — `new_version_display` goes into
 * the "Detect New Version {0}" message header, `body` renders as
 * release notes Markdown, `download_url` is what the "Download" button
 * opens, and `tag_name` is retained for diagnostics / telemetry.
 * 
 * # IPC exposure (P10.3 D4)
 * 
 * Derives [`serde::Serialize`] + [`specta::Type`] so the
 * `check_update` Tauri command returns the struct directly
 * (wrapped in `Option<_>` to distinguish "no newer release" from
 * "newer release found"). `Deserialize` is intentionally **not**
 * derived — the frontend never constructs `UpdateInfo`; it only
 * consumes the backend-minted value, so the reverse direction
 * would be dead surface.
 */
export type UpdateInfo = { 
/**
 * Human-readable version string produced by
 * `format!("{major}.{minor}.{patch}({timestamp})")` — matches
 * WPF L145 `newVerDisplay`.
 */
new_version_display: string; 
/**
 * Markdown body the maintainer wrote on the release page.
 * Forwarded verbatim from [`GitHubRelease::body`].
 */
body: string; 
/**
 * Direct link to the first binary asset (with proxy prefix applied
 * when one was discovered) or — if the release has no assets — a
 * fallback release-tag page URL on `github.com`. See the
 * "`download_url` proxy asymmetry" section in the [module
 * docs][self] for why the fallback is never proxied.
 */
download_url: string; 
/**
 * Original release tag, e.g. `v5.8.3.2604011114`. Retained for
 * logging, analytics, and for the UI layer to link to the release
 * page even when the asset-download URL was provided.
 */
tag_name: string }
/**
 * Captcha image payload for the verify flow — always a
 * `data:image/png;base64,<…>` data URL.
 * 
 * Same shape as [`QrStart::bitmap_base64`] so the Vue layer can
 * use the same `<img :src>` binding for both login bitmap types.
 */
export type VerifyCaptcha = { 
/**
 * Full `data:image/png;base64,<…>` data URL.
 */
image_base64: string }
/**
 * Display-only payload returned by [`get_verify_page_info`].
 * 
 * Carries the exactly one field the UI renders — the auth-type
 * label (e.g. `"請輸入您的電子郵件驗證碼"` / `"Please enter the
 * email verification code"`) so the user understands which
 * second-factor channel the server is asking about. Every other
 * field of the underlying [`VerifyPageInfo`][vpi]
 * (`__VIEWSTATE`, `__EVENTVALIDATION`, `form_action`,
 * `samplecaptcha`) is a server-side state token the backend keeps
 * on [`PendingVerify`].
 * 
 * [vpi]: crate::services::beanfun::verify::VerifyPageInfo
 */
export type VerifyPage = { 
/**
 * `lblAuthType` label text — rendered verbatim in the verify
 * prompt. The UI should localise the surrounding chrome but
 * pass the server-provided text through because it may name
 * a specific registered email / phone number the server
 * wants to verify against.
 */
lbl_auth_type: string }
/**
 * Classified [`submit_verify`] result.
 * 
 * Internally-tagged serde enum mirroring [`QrStatus`] — JSON:
 * 
 * ```json
 * { "result": "success" }
 * { "result": "wrong_captcha" }
 * { "result": "wrong_auth_info" }
 * { "result": "server_message", "message": "..." }
 * ```
 * 
 * Frontend Vue poll / retry loop dispatches on `result`.
 * 
 * - `success` — verify cleared; frontend should now re-run
 * `login_regular` / resume the prior login flow. The backend
 * has already cleared [`PendingVerify`].
 * - `wrong_captcha` — user mistyped the captcha; backend keeps
 * [`PendingVerify`] so `submit_verify` can be retried after a
 * fresh `get_verify_captcha` (same challenge, new captcha
 * image — the captcha id is fixed, rendering differs per GET).
 * - `wrong_auth_info` — user mistyped the auth code; backend
 * keeps [`PendingVerify`] so the user can retry.
 * - `server_message` — server returned a non-success, non-captcha
 * alert (`alert('...')`); WPF surfaces the message verbatim so
 * we do the same, and keep the pending slot for follow-up.
 */
export type VerifySubmit = 
/**
 * `資料已驗證成功` — AdvanceCheck cleared; resume login flow.
 */
{ result: "success" } | 
/**
 * `圖形驗證碼輸入錯誤` — captcha typed wrong.
 */
{ result: "wrong_captcha" } | 
/**
 * Fallback "wrong auth info" classification (email / SMS code
 * rejected).
 */
{ result: "wrong_auth_info" } | 
/**
 * Server alert message — UI should render it verbatim. Matches
 * WPF's "display the `alert('...')` body" branch.
 */
{ result: "server_message"; message: string }
/**
 * Compile-time build metadata returned by [`version`].
 * 
 * `app` is this crate's own version (derived from `Cargo.toml` via
 * the `CARGO_PKG_VERSION` environment variable Cargo sets at build
 * time); `tauri` is the Tauri framework version the binary was
 * compiled against — useful in bug reports to confirm the IPC
 * dispatcher expected by the frontend matches what's running.
 */
export type VersionInfo = { 
/**
 * Our own crate version (`env!("CARGO_PKG_VERSION")` at compile
 * time).
 */
app: string; 
/**
 * Tauri framework version ([`tauri::VERSION`] at compile time).
 */
tauri: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
