use std::path::PathBuf;

use sha2::{Digest, Sha256};

/// LocaleRemulator assets shipped by the WPF tree, in the exact order
/// `MainWindow::startByLR` (L1904-1914) checks them. The runtime
/// `locale_remulator` module `include_bytes!`s the same files with the
/// same ordering, so this list is the single source of truth.
const LR_ASSETS: &[&str] = &[
    "LRConfig.xml",
    "LRHookx32.dll",
    "LRHookx64.dll",
    "LRProc.exe",
    "LRSubMenus.dll",
];

fn main() {
    tauri_build::build();
    emit_lr_sha256();
}

/// Compute the SHA-256 of every LocaleRemulator asset referenced by
/// `LR_ASSETS` and write a Rust source snippet to `$OUT_DIR/lr_sha256.rs`
/// so the runtime module can `include!` a typed const array.
///
/// # Panics
///
/// Build fails if any asset is missing: without the hash we can't
/// enforce the SHA-256 integrity check P8 chunk 8.2 ships as an
/// upgrade over WPF's length-only comparison, and silently skipping
/// would let a tampered DLL sneak through.
fn emit_lr_sha256() {
    let manifest_dir = PathBuf::from(
        std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is always set by cargo"),
    );
    let lr_dir = manifest_dir.join("../../Beanfun/LocaleRemulator");

    println!("cargo:rerun-if-changed=build.rs");

    let mut entries: Vec<(String, [u8; 32])> = Vec::with_capacity(LR_ASSETS.len());
    for name in LR_ASSETS {
        let path = lr_dir.join(name);
        println!("cargo:rerun-if-changed={}", path.display());

        let bytes = std::fs::read(&path).unwrap_or_else(|err| {
            panic!(
                "LocaleRemulator asset `{name}` is required for the runtime integrity check \
                 but could not be read from `{}`: {err}. The WPF tree at Beanfun/LocaleRemulator/ \
                 must contain this file for beanfun-next to build.",
                path.display()
            )
        });

        let digest: [u8; 32] = Sha256::digest(&bytes).into();
        entries.push((name.to_string(), digest));
    }

    let out_dir = PathBuf::from(
        std::env::var("OUT_DIR").expect("OUT_DIR is always set by cargo for build scripts"),
    );
    let out_file = out_dir.join("lr_sha256.rs");
    std::fs::write(&out_file, render_sha256_table(&entries))
        .unwrap_or_else(|err| panic!("failed to write `{}`: {err}", out_file.display()));
}

/// Render the computed `(name, sha256)` pairs into a Rust source
/// snippet that the runtime module `include!`s. Kept as a separate
/// pure function so the format stays reviewable in one place.
fn render_sha256_table(entries: &[(String, [u8; 32])]) -> String {
    let mut out = String::new();
    out.push_str("// @generated by build.rs — LocaleRemulator SHA-256 table.\n");
    out.push_str("// Do not edit; regenerate by rebuilding with updated binaries under\n");
    out.push_str("// `Beanfun/LocaleRemulator/`.\n\n");
    out.push_str("pub(crate) const LR_SHA256: [(&str, [u8; 32]); ");
    out.push_str(&entries.len().to_string());
    out.push_str("] = [\n");
    for (name, digest) in entries {
        out.push_str("    (\"");
        out.push_str(name);
        out.push_str("\", [");
        for (idx, byte) in digest.iter().enumerate() {
            if idx > 0 {
                out.push_str(", ");
            }
            out.push_str(&format!("0x{byte:02x}"));
        }
        out.push_str("]),\n");
    }
    out.push_str("];\n");
    out
}
